name: Compilar APK Flutter

on:
  push:
    branches: [ main, master, principal ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Crear configuracion Android
        run: |
          mkdir -p temp_backup
          cp lib/main.dart temp_backup/main.dart
          flutter create . --platforms=android --overwrite
          cp temp_backup/main.dart lib/main.dart

      - name: Obtener dependencias
        run: flutter pub get

      - name: Compilar APK ejecutable
        run: flutter build apk --release --no-tree-shake-icons

      - name: Guardar archivo APK
        uses: actions/upload-artifact@v4
        with:
          name: YoLeo-App-Minedu
          path: build/app/outputs/flutter-apk/app-release.apk
